console.log("Hello")
console.log("yuphada")
console.log("nattaporn")
console.log("nong do kon bar")
console.log("nong do dek ven")
console.log("nong do na ma")
console.log("ในขณะที่เพื่อนโดกำลังเครียดอยู่นั้น เพื่อนยุได้ทำการนั่งขำกับข้อความที่พิมพ์ขึ้น git อย่างมีความสุข")